site_name: ⚜️ Clientele
site_url: https://beckett-software.github.io/clientele/
theme:
  name: material
  palette:
    primary: black

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Compatibility: compatibility.md
  - Client Example: examples.md
  - Change log: CHANGELOG.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
