[tool.poetry]
name = "popenapi"
version = "0.1.0"
description = "Typed Python OpenAPI Client"
authors = ["Paul Hallett <paulandrewhallett@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.scripts]
popenapi = "src.cli:cli_group"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.24.1"
click = "^8.1.3"
pytz = "^2023.3"
types-pytz = "^2023.3.0.0"
structlog = "^23.1.0"
openapi3-parser = "^1.1.10"
ipython = "^8.14.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "1.4.0"
ruff = "^0.0.272"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001"
]
