name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Ruff Check
      # You may pin to the exact commit or the version.
      # uses: jpetrucciani/ruff-check@33f3725e751a187bb666b7d7a7094d38a2df12db
      uses: jpetrucciani/ruff-check@0.0.239
      with:
        # File or directory to run ruff on
        path: src/
        # Optional ruff flags (refer to `ruff --help`)
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      env:
          POETRY_VIRTUALENVS_CREATE: false
    - name: Black check
      run: |
          black src/ --check
    - name: Test with pytest
      run: |
          pytest -vv
